name: cadet-process
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cadet
  - jupyter_contrib_nbextensions
  - pip
  - pip:
    - cadet-process
    - sphinx>=2.2.0
    - sphinx-gallery>=0.10.0
    - sphinxcontrib-bibtex>=2.4.1
    - sphinx_book_theme>=0.2.0
    - sphinx-sitemap>=2.2.0
    - numpydoc>=1.2
    - myst-nb>=0.13.2
